#!/usr/bin/env ruby

require 'bio/plan/shellcheck'

Bio::Plan::ShellCheck::option :bio_cli,
  long: '--hab-cli CLI',
  default: 'hab',
  description: 'Set binary to use. Defaults to hab'

Bio::Plan::ShellCheck.new.run
