#!{{pkgPathFor "core/bash"}}/bin/bash
# -*- mode: shell-script -*-
# shellcheck shell=bash

exec 2>&1

set -e

source '{{pkg.svc_config_path}}/functions.sh'

if [[ ! -f "{{pkg.svc_data_path}}/pgdata/PG_VERSION" ]]; then
    exec echo 0
fi

local_lsn_position
